
name: buil-test-deploy
# trigger
on: push
# jobs to perform when trigger takes place
jobs: 
  # job name
  build:
    # target OS
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup and use node js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build
  test: 
    # waits for build job to finish
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: setup and use node js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        - run: npm install
        # runs all tests
        - run: npm test
  deploy: 
    # waits for test job to finish
    needs: test
    # machine OS image
    runs-on: ubuntu-latest
    # this is the environment where your app will be 
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}\
    # permissions for what this job can do 
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
        # checkout repo
        - name: checkout repo
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        # setup node on machine
        - name: use node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        # configure guthub pages to accept a static site
        - name: configure github pages
          uses: actions/configure-pages@v3
          with:
            static_site_generator: next
        - run: npm install
        - run: npm run build
        # upload the stuff that was generated by npm run build which in this case ends up in the out folder in the app
        - name: upload artificats
          uses: actions/upload-pages-artifact@v1
          with:
            path: "./out"
        # deploy to pages
        - name: deploy
          id: deployment
          uses: actions/deploy-pages@v1

      


